service: ats-integration-microservice

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    ATS_PROVIDER: ${env:ATS_PROVIDER, 'greenhouse'}
    ATS_API_KEY: ${env:ATS_API_KEY, 'mock-api-key'}
    ATS_BASE_URL: ${env:ATS_BASE_URL, 'https://api.mockats.com'}
    ATS_ACCOUNT_ID: ${env:ATS_ACCOUNT_ID, ''}
    ZOHO_CLIENT_ID: ${env:ZOHO_CLIENT_ID, ''}
    ZOHO_CLIENT_SECRET: ${env:ZOHO_CLIENT_SECRET, ''}
    ZOHO_REFRESH_TOKEN: ${env:ZOHO_REFRESH_TOKEN, ''}
    ZOHO_BASE_URL: ${env:ZOHO_BASE_URL, 'https://recruit.zoho.com/recruit/v2'}
    ZOHO_TOKEN_URL: ${env:ZOHO_TOKEN_URL, 'https://accounts.zoho.com/oauth/v2/token'}

functions:
  getJobs:
    handler: handler.get_jobs
    timeout: 30 
    events:
      - http:
          path: jobs
          method: get

  createCandidate:
    handler: handler.create_candidate
    events:
      - http:
          path: candidates
          method: post

  getApplications:
    handler: handler.get_applications
    events:
      - http:
          path: applications
          method: get

plugins:
  - serverless-offline

custom:
  pythonRequirements:
    dockerizePip: false
